version: '3'
services:
  db-1:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_1_PASSWORD}
      - POSTGRES_USER=${DB_1_USER}
      - POSTGRES_DB=db-1
    ports:
      - "5432:5432"
  db-3:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_3_PASSWORD}
      - POSTGRES_USER=${DB_3_USER}
      - POSTGRES_DB=db-3
    ports:
      - "5433:5432"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    environment:
      - WDS_SOCKET_PORT=0
    ports:
      - "4000:4000"
    volumes:
      - ./client:/app
  backend-1:
    build:
      context: ./rails-backend-1
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./rails-backend-1:/app
    depends_on:
      - db-1
    environment:
      - DB_1_PASSWORD=${DB_1_PASSWORD}
      - DB_1_USER=${DB_1_USER}
  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./flask:/app
    depends_on:
      - db-3
    environment:
      - DB_3_PASSWORD=${DB_3_PASSWORD}
      - DB_3_USER=${DB_3_USER}
