apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-green-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
      version: v1.0.6
  template:
    metadata:
      labels:
        app: client
        version: v1.0.6
    spec:
      containers:
        - name: client
          image: mterrano1/case-tracker-deploy-example:1.0.6
          ports:
            - containerPort: 4000
          env:
            - name: WDS_SOCKET_PORT
              value: "0"
      imagePullSecrets:
        - name: regcred