apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client
      version: v1.2.5
  template:
    metadata:
      labels:
        app: client
        version: v1.2.5
    spec:
      containers:
        - name: client
          image: mterrano1/case-tracker-client:1.2.5
          ports:
            - containerPort: 4000
          env:
            - name: WDS_SOCKET_PORT
              value: "0"
      imagePullSecrets:
        - name: regcred